apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
    - 10.10.0.30/32 # the IP I assigned to ingress must be in the pool
    - 10.10.0.31/32
    - 10.10.0.32/32
    - 10.10.0.33/32
    - 10.10.0.34/32
    - 10.10.0.35/32
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
    - default
